### PR TITLE
Fix issue 11: Only assign  issues from the specified project

### LINKED ISSUE #11: Prevent issues created in other projects from being assigned
If a user in the specified project is a part of multiple projects, new issues for any of those projects will have the round robin assignments applied to them

Basically the `SENTRY_PROJECT_ID` env variable specifies which users to assign in round robin (members of that project), but webhook requests will be sent for issues created in _any_ project in the organization.

When an issue is created in a project that is not `SENTRY_PROJECT_ID`, a webhook request is still sent and the Round Robin app attempts to assign the issue to the user list from the `SENTRY_PROJECT_ID` project. This "works" if there are any overlapping users, but if there is no user that belongs to the project, then the app throws an error

### PR DESCRIPTION
**Pull request by LearningNerd**
Fixes #11 so now issues are only assigned if they belong to the specified project. Thanks @nolachen, good catch! Also added a test for this.

### CODE REVIEW

File: app.js [hunk 1]
```diff
@@ -39,20 +39,25 @@ app.post("/", async function(request, response) {
...
-    await assignNextUser(issueID);
 
-    if (sentry) {
-      sentry.addBreadcrumb({
-        message: `New issue created. issueID: ${issueID}`,
-        level: sentry.Severity.Info
-      });
+    const {id:newIssueProjectID} = request.body.data.issue.project;
+    // Only continue if this issue is for the project specified in .env
+    if (newIssueProjectID === projectID) {
```
Comment (scefali) [inline app.js]: @LearningNerd We should probably send a `202` status code when `newIssueProjectID` is different than `projectID`.

Comment (manuzope) [reply app.js]: Hmmm, [`202 Accepted`](https://httpstatuses.com/202) says that we've accepted the event but processing hasn't yet completed. Maybe a `400 Bad Request`?

Comment (scefali) [reply app.js]: I don't think it makes sense to send a bad request because it's not a bad request. We just aren't doing anything with the request. That's why I think a `202` makes sense.

Comment (scefali) [reply app.js]: @manuzope But based off our code I see it's mostly used when kicking off async jobs. So I guess that `202` is probably not appropriate.

Comment (manuzope) [reply app.js]: Yea 202s are good when you take an event and put it on a queue. There isn't a great status code for this use case. 200 OK is a good enough option, imo.

Comment (LearningNerd) [reply app.js]: Thanks for the context on this, I wasn't familiar!
